### ISSUE TITLE
OSError: Can not find Xvfb. Please install it and try again

### ISSUE THREAD

**Issue by christoph-buente** [StegSchreck/HistoricMarketPriceDownloader#2]
I'm trying to run the Downloader with Python 3.9.10 in a virtualenv on Mac OS big sure 11.6.3 But I get this error:
```
❯ python3 main.py --isin IE00B4L5YC18
Traceback (most recent call last):
  File "/Users/christoph/Projects/HistoricMarketPriceDownloader/main.py", line 38, in <module>
    main()
  File "/Users/christoph/Projects/HistoricMarketPriceDownloader/main.py", line 16, in main
    ariva = Ariva(args)
  File "/Users/christoph/Projects/HistoricMarketPriceDownloader/ariva.py", line 16, in __init__
    self._init_browser()
  File "/Users/christoph/Projects/HistoricMarketPriceDownloader/ariva.py", line 24, in _init_browser
    self.browser_handler = BrowserHandler(self.args)
  File "/Users/christoph/Projects/HistoricMarketPriceDownloader/browser_handler.py", line 18, in __init__
    self.display = Xvfb()
  File "/opt/homebrew/lib/python3.9/site-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)
OSError: Can not find Xvfb. Please install it and try again.
```

Any idea what is going on? I checked for XVFB on mac and my understanding is, that this is more related to linux.

**Comment by StegSchreck** [comment]
Hey, yes. 
You will need to install Xvfb, as the error states. This is also mentioned in the [Readme](https://github.com/StegSchreck/HistoricMarketPriceDownloader#preconditions)


On e.g. Arch Linux, this would be `pacman -S extra/xorg-server-xvfb`
